# Generated by Django 5.1.6 on 2025-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_text_tag_name_article_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
