# Generated by Django 5.1.6 on 2025-03-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, default='a', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
