# Generated by Django 5.1.6 on 2025-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chunked',
            field=models.BooleanField(default=False),
        ),
    ]
