# Generated by Django 5.1.6 on 2025-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_chunked'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
