services:
  django:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - .env  # Ensure this file contains database credentials
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: "gunicorn research.wsgi:application --bind 0.0.0.0:8000"
