services:
  django:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - .env  # Ensure this file contains database credentials
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    volumes:
      - .:/app
    command: gunicorn research.wsgi:application --bind 0.0.0.0:8000

  weaviate:
    image: semitechnologies/weaviate:1.22.3
    container_name: weaviate
    restart: always
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
