# Generated by Django 5.1.6 on 2025-02-13 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('notes', '0002_questionbank_articlequestion_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlequestion",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="articles.article",  # Now referencing `articles.Article`
            ),
        ),
    ]
