# Generated by Django 5.1.6 on 2025-03-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_articlequestion_article_delete_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
